// day1/client/src/views/Login.vue
<template>
    <div class="login">
        <van-field v-model="user" placeholder="请输入用户名" />
        <van-field v-model="pwd" type="password" placeholder="请输入密码" />
        <van-button type="info" v-show="!click" @click="loginIn('/login')">登录</van-button>
        <p v-show="!click" @click="click = !click">没有账号？去注册</p>
        <van-button type="primary" v-show="click" @click="loginIn('/registry')">注册</van-button>
        <p v-show="click" @click="click = !click">已有账号？去登陆</p>
    </div>
</template>

<script>
export default {
    data() {
        return {
            user: '',
            pwd: '',
            click: false,
        };
    },
    methods: {
        async loginIn(url) {
            const { pwd, user, $request, $router } = this;
            if (user === '') return alert('大兄弟 看看账号');
            if (pwd === '') return alert('大兄弟 看看密码');
            const sendObj = { user, pwd };
            let res = await $request('post', url, sendObj);
            alert(res.data.message);
            if (res.data.code === 0) {
                localStorage.setItem('token', res.data.token);
                $router.push('/home');
            }
            if (res.data.code === 2) {
                this.click = !this.click;
            }
        },
    },
};
</script>

<style></style>

// react-project/client/src/views/login.js
import React, { Component } from 'react';
import { Form, Icon, Input, Button } from 'antd';
class login extends Component {
    handleSubmit = e => {
        let _this = this;
        e.preventDefault();
        this.props.form.validateFields((err, values) => {
            if (!err) {
                this.$request('post', '/login', values).then(res => {
                    if (res.data.code === 0) {
                        localStorage.setItem('token', res.data.data.token);
                        localStorage.setItem('username', res.data.data.user);
                        _this.props.history.push('/home');
                    } else {
                        alert(res.data.msg);
                    }
                });
            }
        });
    };

    render() {
        const { getFieldDecorator } = this.props.form;
        return (
            <div className="login">
                <div style={{ textAlign: 'center' }}>
                    <h3>
                        登录<small>login</small>
                    </h3>
                </div>
                <Form onSubmit={this.handleSubmit} className="login-form">
                    <Form.Item>
                        {getFieldDecorator('user', {
                            rules: [{ required: true, message: '请输入你的用户名!' }],
                        })(<Input prefix={<Icon type="user" />} placeholder="Username" />)}
                    </Form.Item>
                    <Form.Item>
                        {getFieldDecorator('pwd', {
                            rules: [{ required: true, message: '请输入你的密码!' }],
                        })(
                            <Input
                                prefix={<Icon type="lock" />}
                                type="password"
                                placeholder="Password"
                            />
                        )}
                    </Form.Item>
                    <Form.Item>
                        <Button
                            type="primary"
                            htmlType="submit"
                            className="login-form-button"
                            block
                        >
                            登录
                        </Button>
                    </Form.Item>
                </Form>
            </div>
        );
    }
}

export default Form.create({ name: 'normal_login' })(login);
